include:
  - README.md  # 明确包含 README.md
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: zZ notes
description: personal feelings.

email: vbhvvikas@gmail.com
favicon: false
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jemoji

navigation:
  - name: Home Page
    link: ./
