include:
  - README.md  # 明确包含 README.md
baseurl: ""  # 如果是用户站点 (username.github.io)，留空；如果是项目站点 (username.github.io/repo)，设为 "/repo"
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: zZ notes
description: personal feelings.

email: webnwww@gmail.com
favicon: false
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jemoji

navigation:
  - name: Home Page
    link: ./
