include:
  - README.md  # 明确包含 README.md
# The Site Configuration
baseurl: ""  # 如果是用户站点 (username.github.io)，留空；如果是项目站点 (username.github.io/repo)，设为 "/repo"
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: .zZ's notes
email: ggwebn@gmail.com
description: personal feelings
favicon: false
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji


navigation:
  - name: Readme
    link: ./index.html

