include:
  - README.md  # 明确包含 README.md
# The Site Configuration
remote_theme: daattali/beautiful-jekyll
title: notes
author: zZ
navbar-links:
  关于我: "about"

social-network-links:
  email: "ggwebn@gmail.com"
rss: true  # 启用 RSS
