include:
  - README.md  # 明确包含 README.md
# The Site Configuration
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
baseurl: ""  # 如果是用户站点 (username.github.io)，留空；如果是项目站点 (username.github.io/repo)，设为 "/repo"
title: zZ notes
description: Personal Feelings
email: ggwebn@gmail.com
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  
navigation:
  - name: Home Page
    link: ./
