include:
  - README.md  # 明确包含 README.md
# The Site Configuration
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: .zZ's notes
email: ggwebn@gmail.com
description: personal feelings
favicon: false
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji


navigation:
  - name: Readme
    link: ./index.html

