include:
  - README.md  # 明确包含 README.md
# The Site Configuration
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: zZ notes
description: Personal Feelings
email: ggwebn@gmail.com
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  
navigation:
  - name: Home Page
    link: ./
